import { useEffect, useState } from 'react';
import DataTable from '../../components/common/DataTable';
import PageHeader from '../../components/common/PageHeader';
import { useLanguage } from '../../context/LanguageContext';
import { getManagerKpisApi } from '../../services/managerService';

const Analytics = () => {
    const { language } = useLanguage(); const vi=language==='vi';
    const [data,setData]=useState(null); const [error,setError]=useState('');
    useEffect(()=>{getManagerKpisApi().then(r=>r.success?setData(r.data):setError(r.message));},[]);
    const exportCsv=()=>{if(!data)return;const header=['Project','Tasks','Completed','Overdue','Completion rate','Open incidents'];const rows=data.projects.map(p=>[p.name,p.tasks,p.completed,p.overdue,`${p.completion_rate}%`,p.open_incidents]);const quote=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv='\uFEFF'+[header,...rows].map(row=>row.map(quote).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`manager-kpi-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);};
    const projectColumns=[{key:'name',label:vi?'Dự án':'Project',cellClassName:'font-semibold text-slate-900'},{key:'tasks',label:vi?'Công việc':'Tasks'},{key:'completed',label:vi?'Hoàn thành':'Completed'},{key:'overdue',label:vi?'Quá hạn':'Overdue',render:r=><span className="font-semibold text-rose-600">{Number(r.overdue||0)}</span>},{key:'completion_rate',label:vi?'Tỷ lệ hoàn thành':'Completion rate',render:r=><span className="badge badge-info">{r.completion_rate}%</span>},{key:'open_incidents',label:vi?'Sự cố mở':'Open incidents'}];
    const engineerColumns=[{key:'fullname',label:vi?'Kỹ sư':'Engineer',cellClassName:'font-semibold text-slate-900'},{key:'tasks',label:vi?'Tổng việc':'Tasks'},{key:'completed',label:vi?'Hoàn thành':'Completed'},{key:'overdue',label:vi?'Quá hạn':'Overdue',render:r=><span className="font-semibold text-rose-600">{Number(r.overdue||0)}</span>},{key:'completion_rate',label:vi?'Hiệu suất đúng quy trình':'Completion rate',render:r=>`${r.completion_rate}%`}];
    return <div className="space-y-6"><PageHeader title={vi?'Báo cáo điều hành':'Management analytics'} subtitle={vi?'KPI tiến độ theo dự án và kỹ sư.':'Project and engineer delivery KPIs.'} icon="activity" action={<div className="flex gap-2"><button className="btn btn-outline" disabled={!data} onClick={exportCsv}>{vi?'Xuất Excel (CSV)':'Export CSV'}</button><button className="btn btn-primary" onClick={()=>window.print()}>{vi?'In / Lưu PDF':'Print / Save PDF'}</button></div>}/>{error&&<div className="alert alert-error">{error}</div>}{!data?<div className="rounded-3xl bg-white p-10 text-center text-slate-500">{vi?'Đang tải...':'Loading...'}</div>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[[vi?'Tổng công việc':'Tasks',data.summary.tasks],[vi?'Đã hoàn thành':'Completed',data.summary.completed],[vi?'Quá hạn':'Overdue',data.summary.overdue],[vi?'Báo cáo đã duyệt':'Approved reports',data.summary.approved_reports],[vi?'Giờ duyệt trung bình':'Avg review hours',data.summary.avg_review_hours??0]].map(([label,value])=><div key={label} className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-slate-900">{value||0}</p></div>)}</div><section><h2 className="mb-4 text-lg font-semibold text-slate-900">{vi?'Theo dự án':'By project'}</h2><DataTable columns={projectColumns} data={data.projects}/></section><section><h2 className="mb-4 text-lg font-semibold text-slate-900">{vi?'Theo kỹ sư':'By engineer'}</h2><DataTable columns={engineerColumns} data={data.engineers}/></section></>}</div>;
};
export default Analytics;
