import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import DataTable from '../../components/common/DataTable';
import PageHeader from '../../components/common/PageHeader';
import { useLanguage } from '../../context/LanguageContext';
import { getProjectWorkspaceApi } from '../../services/projectService';

const ProjectWorkspace = () => {
    const { id } = useParams(); const { language } = useLanguage(); const vi=language==='vi';
    const [data,setData]=useState(null); const [error,setError]=useState(''); const [tab,setTab]=useState('overview');
    useEffect(()=>{getProjectWorkspaceApi(id).then(r=>r.success?setData(r.data):setError(r.message));},[id]);
    const tabs=[['overview',vi?'Tổng quan':'Overview'],['tasks',vi?'Công việc':'Tasks'],['engineers',vi?'Kỹ sư':'Engineers'],['reports',vi?'Báo cáo':'Reports'],['incidents',vi?'Sự cố':'Incidents'],['documents',vi?'Tài liệu':'Documents']];
    const taskColumns=useMemo(()=>[{key:'title',label:vi?'Công việc':'Task',cellClassName:'font-semibold text-slate-900'},{key:'engineer_name',label:vi?'Kỹ sư':'Engineer'},{key:'due_date',label:vi?'Hạn':'Due date',render:r=>r.due_date?new Date(r.due_date).toLocaleDateString(vi?'vi-VN':'en-US'):'—'},{key:'priority',label:vi?'Ưu tiên':'Priority'},{key:'status',label:vi?'Trạng thái':'Status',render:r=><span className="badge badge-info">{r.status}</span>},{id:'checklist',label:'Checklist',render:r=>`${Number(r.checklist_completed||0)}/${Number(r.checklist_total||0)}`}],[vi]);
    if(error)return <div className="alert alert-error">{error}</div>; if(!data)return <div className="rounded-3xl bg-white p-10 text-center text-slate-500">{vi?'Đang tải không gian dự án...':'Loading project workspace...'}</div>;
    const {project}=data; const completed=data.tasks.filter(t=>t.status==='completed').length; const overdue=data.tasks.filter(t=>['pending','in_progress','on_hold'].includes(t.status)&&t.due_date&&new Date(t.due_date)<new Date()).length; const progress=data.tasks.length?Math.round(100*completed/data.tasks.length):0;
    return <div className="space-y-6"><PageHeader title={project.name} subtitle={`${project.location} · ${new Date(project.start_date).toLocaleDateString(vi?'vi-VN':'en-US')} — ${new Date(project.end_date).toLocaleDateString(vi?'vi-VN':'en-US')}`} icon="projects" action={<Link className="btn btn-outline" to="/manager/projects">{vi?'Quay lại dự án':'Back to projects'}</Link>}/><div className="flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`min-w-max rounded-xl px-4 py-2 text-sm font-semibold ${tab===key?'bg-indigo-600 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div>
        {tab==='overview'&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[vi?'Tiến độ':'Progress',`${progress}%`],[vi?'Tổng công việc':'Tasks',data.tasks.length],[vi?'Quá hạn':'Overdue',overdue],[vi?'Sự cố đang mở':'Open incidents',data.incidents.filter(i=>i.status!=='resolved').length]].map(([label,value])=><div key={label} className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-slate-900">{value}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-900">{vi?'Mô tả dự án':'Project description'}</h2><p className="mt-3 whitespace-pre-wrap text-slate-600">{project.description||'—'}</p></section><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-900">{vi?'Tóm tắt phê duyệt':'Approval summary'}</h2><p className="mt-3 text-slate-600">{vi?'Báo cáo chờ duyệt':'Pending reports'}: <strong>{data.reports.filter(r=>r.approval_status==='pending').length}</strong></p><p className="mt-2 text-slate-600">{vi?'Sự cố mức cao/nghiêm trọng':'High/critical incidents'}: <strong>{data.incidents.filter(i=>['high','critical'].includes(i.severity)&&i.status!=='resolved').length}</strong></p></section></div></>}
        {tab==='tasks'&&<DataTable columns={taskColumns} data={data.tasks} emptyText={vi?'Chưa có công việc.':'No tasks.'}/>} 
        {tab==='engineers'&&<DataTable columns={[{key:'fullname',label:vi?'Kỹ sư':'Engineer',cellClassName:'font-semibold text-slate-900'},{key:'employee_code',label:vi?'Mã nhân viên':'Employee code'},{key:'tasks',label:vi?'Tổng việc':'Tasks'},{key:'active_tasks',label:vi?'Việc đang mở':'Active tasks'}]} data={data.engineers}/>} 
        {tab==='reports'&&<DataTable columns={[{key:'task_title',label:vi?'Công việc':'Task',cellClassName:'font-semibold text-slate-900'},{key:'engineer_name',label:vi?'Kỹ sư':'Engineer'},{key:'approval_status',label:vi?'Phê duyệt':'Approval',render:r=><span className="badge badge-info">{r.approval_status}</span>},{key:'created_at',label:vi?'Ngày gửi':'Submitted',render:r=>new Date(r.created_at).toLocaleString(vi?'vi-VN':'en-US')}]} data={data.reports}/>} 
        {tab==='incidents'&&<DataTable columns={[{key:'title',label:vi?'Sự cố':'Incident',cellClassName:'font-semibold text-slate-900'},{key:'engineer_name',label:vi?'Người báo':'Reporter'},{key:'severity',label:vi?'Mức độ':'Severity'},{key:'assigned_to_name',label:vi?'Phụ trách':'Owner',render:r=>r.assigned_to_name||'—'},{key:'status',label:vi?'Trạng thái':'Status',render:r=><span className="badge badge-warning">{r.status}</span>}]} data={data.incidents}/>} 
        {tab==='documents'&&<><div className="mb-3 flex justify-end"><Link className="btn btn-primary" to="/manager/documents">{vi?'Quản lý tài liệu':'Manage documents'}</Link></div><DataTable columns={[{key:'title',label:vi?'Tài liệu':'Document',cellClassName:'font-semibold text-slate-900'},{key:'version',label:vi?'Phiên bản':'Version',render:r=>`v${r.version}`},{key:'file_name',label:vi?'Tên file':'File name'},{key:'uploaded_by_name',label:vi?'Người tải':'Uploaded by'},{key:'created_at',label:vi?'Ngày tải':'Uploaded',render:r=>new Date(r.created_at).toLocaleString(vi?'vi-VN':'en-US')}]} data={data.documents}/></>}
    </div>;
};
export default ProjectWorkspace;
